default:
    method: "hlt_stoch"
    max_steps: 100
    max_frames: 1000000
    frame_skip: 1
    model_lr: !!float 3e-3
    policy_lr: !!float 3e-3
    value_lr: !!float 3e-4
    soft_q_lr: !!float 3e-4
    reward_scale: 1.0
    horizon: 10 # for half cheetah
    model_iter: 5
    trajectory_samples: 60
    lam: 0.2
    activation_fun: 'ReLU'
