default:
    method: "hlt_deter"
    max_steps: 100
    max_frames: 1000000
    frame_skip: 1
    model_lr: !!float 3e-3
    policy_lr: !!float 3e-3
    value_lr: !!float 3e-4
    soft_q_lr: !!float 3e-4
    planner_lr: 0.1
    reward_scale: 1.0
    horizon: 5
    model_iter: 5
#     lam: 0.1
    activation_fun: 'ReLU'
